---
Logo: fs2020
Regexes:
  Button: Button\s*(\d+)
  Axis: (?:([R])-)?Axis\s*([XYZ])
  Pov: (?i)Pov(\d?)[\s_]([[:alpha:]]+)
  Rotation: Rotation\s*([XYZ])
  Slider: Slider\s*([XYZ])
InputMap: # Devices with known game inputs and which model input they map to
  044FB106:
    Slider: { X: U }
  LogitechExtreme3DPro:
    Slider: { X: U }
  SaitekX56Throttle:
    Axis: { RX: RZ, RY: U, RZ: V }
    Slider: { X: RX, Y: RY }
  T16000M:
    Slider: { X: U }
  T16000MFCS:
    Slider: { X: U }
  T16000MTHROTTLE:
    Rotation: { X: X, Y: Y }
    Slider: { X: X, Y: Y }
  ThrustMasterHOTAS4:
    Slider: { X: Z }
  ThrustMasterHOTASOne:
    Slider: { X: Z }
  ThrustMasterTFlightHOTASX:
    Slider: { X: Z }
  ThrustMasterWarthogThrottle:
    Slider: { X: Z }
  T-Rudder:
    Rotation: { X: X, Y: Y }
    Slider: { Y: Z }
InputLabels:
  CHECKLIST : "Display Checklist"
  KEY_ACTIVE_PAUSE_TOGGLE : "Active Pause"
  KEY_AILERON_TRIM_LEFT : "Aileron Trim Left"
  KEY_AILERON_TRIM_RIGHT : "Aileron Trim "
  KEY_ALL_LIGHTS_TOGGLE : "All External Lights"
  KEY_ALTERNATOR_OFF: "Alternator Off"
  KEY_ALTERNATOR_ON: "Alternator On"
  KEY_ALTERNATOR_SET: "Set Alternator"
  KEY_ANTI_ICE_TOGGLE : "Toggle Anti Ice"
  KEY_AP_MASTER : "AutoPilot Master"
  KEY_APU_STARTER : "APU Starter"
  KEY_AVIONICS_MASTER_1_OFF: "Avionics Master 1 Off"
  KEY_AVIONICS_MASTER_1_ON: "Avionics Master 1 On"
  KEY_AVIONICS_MASTER_1_SET: "Set Avionics Master 1"
  KEY_AVIONICS_MASTER_2_OFF: "Avionics Master 2 Off"
  KEY_AVIONICS_MASTER_2_ON: "Avionics Master 2 On"
  KEY_AVIONICS_MASTER_2_SET: "Set Avionics Master 2"
  KEY_AVIONICS_MASTER_SET: "Set Avionics Master"
  KEY_AXIS_AILERONS_SET : "Ailerons"
  KEY_AXIS_ELEV_TRIM_SET : "Elevator Trim"
  KEY_AXIS_ELEVATOR_SET : "Elevator"
  KEY_AXIS_FLAPS_SET : "Flaps"
  KEY_AXIS_LEFT_BRAKE_SET : "Left Brake"
  KEY_AXIS_MIXTURE_SET : "Mixture"
  KEY_AXIS_RIGHT_BRAKE_SET : "Right Brake"
  KEY_AXIS_RUDDER_SET : "Rudder"
  KEY_BAROMETRIC : "Set Altimeter"
  KEY_BEACON_LIGHTS_SET: "Set Beacon Lights"
  KEY_BRAKES : "Brakes"
  KEY_CAMERACHASE_RESET : "Reset Ext View"
  KEY_CHASE_FREELOOK_HRZ_SET : "Ext Cam Horizontal"
  KEY_CHASE_FREELOOK_VRTC_SET : "Ext Cam Vertical"
  KEY_CHASE_LOOK_DOWN : "Ext Look Down"
  KEY_CHASE_LOOK_LEFT : "Ext Look Left"
  KEY_CHASE_LOOK_RIGHT : "Ext Look Right"
  KEY_CHASE_LOOK_UP : "Ext Look Up"
  KEY_CHASE_QUICKVIEW1 : "Ext View Left"
  KEY_CHASE_QUICKVIEW2 : "Ext Quickview Down"
  KEY_CHASE_QUICKVIEW3 : "Ext Quickview Right"
  KEY_CHASE_QUICKVIEW4 : "Ext Quickview Up"
  KEY_COCKPIT_BACKCYCLE : "Previous Instrument"
  KEY_COCKPIT_CAMERA_HEIGHT_DEC : "Cockpit Move Down"
  KEY_COCKPIT_CAMERA_HEIGHT_INC : "Cockpit Move Up"
  KEY_COCKPIT_CAMERA_SLIDE_BACK : "Cockpit Move Back"
  KEY_COCKPIT_CAMERA_SLIDE_FRONT : "Cockpit Move Forward"
  KEY_COCKPIT_CAMERA_SLIDE_LEFT : "Cockpit Move Left"
  KEY_COCKPIT_CAMERA_SLIDE_RIGHT : "Cockpit Move Right"
  KEY_COCKPIT_CYCLE : "Next Instrument"
  KEY_COCKPIT_FREELOOK_HRZ_SET : "Cockpit Horiztonal"
  KEY_COCKPIT_FREELOOK_VRTC_SET : "Cockpit Vertical"
  KEY_COCKPIT_INSTR_DOWN : "Instrument View Down"
  KEY_COCKPIT_INSTR_LEFT : "Instrument View Left"
  KEY_COCKPIT_INSTR_RIGHT : "Instrument View Right"
  KEY_COCKPIT_INSTR_UP : "Instrument View Up"
  KEY_COCKPIT_INSTRUMENT1 : "Toggle Instrument View 1"
  KEY_COCKPIT_LOOK_DOWN : "Cockpit Look Down"
  KEY_COCKPIT_LOOK_LEFT : "Cockpit Look Left"
  KEY_COCKPIT_LOOK_RIGHT : "Cockpit Look Right"
  KEY_COCKPIT_LOOK_UP : "Cockpit Look Up"
  KEY_COCKPIT_QUICKVIEW3 : "Cockpit Quickview Right"
  KEY_COCKPIT_QUICKVIEW4 : "Cockpit Quickview Left"
  KEY_COCKPIT_RESET : "Reset Cockpit Cam"
  KEY_COCKPIT_UPPER : "Cockpit Upper"
  KEY_CYCLE_PILOTVIEW_BACK : "Cockpit Prev Pilot"
  KEY_CYCLE_PILOTVIEW_NEXT : "Cockpit Next Pilot"
  KEY_ELEV_TRIM_DN : "Elevator Trim Down"
  KEY_ELEV_TRIM_UP : "Elevator Trim Up"
  KEY_ENGINE : "Select Engine"
  KEY_ENGINE_AUTO_START : "Auto Start Engine"
  KEY_FLAPS_DECR : "Decrease Flaps"
  KEY_FLAPS_DOWN : "Extend Flaps"
  KEY_FLAPS_INCR : "Increase Flaps"
  KEY_FLAPS_UP : "Retract Flaps"
  KEY_GEAR_DOWN : "Landing Gear Down"
  KEY_GEAR_TOGGLE : "Landing Gear"
  KEY_GEAR_UP : "Landing Gear Up"
  KEY_HEADING_GYRO_SET : "Set Heading Indicator"
  KEY_LANDING_LIGHTS_SET: "Set Landing Lights"
  KEY_MAGNETO_BOTH: "Magnetos Both"
  KEY_MAGNETO_DECR: "Magnetos Decrease"
  KEY_MAGNETO_INCR: "Magnetos Increase"
  KEY_MAGNETO_LEFT: "Magnetos Left"
  KEY_MAGNETO_OFF: "Magnetos Off"
  KEY_MAGNETO_RIGHT: "Magnetos Right"
  KEY_MAGNETO_SET: "Set Magnetos"
  KEY_MAGNETO_START: "Magnetos Start"
  KEY_MAGNETO: "Magneto"
  KEY_MAGNETO1_BOTH: "Magneto 1 Both"
  KEY_MAGNETO1_DECR: "Magneto 1 Decrease"
  KEY_MAGNETO1_INCR: "Magneto 1 Increase"
  KEY_MAGNETO1_LEFT: "Magneto 1 Left"
  KEY_MAGNETO1_OFF: "Magneto 1 Off"
  KEY_MAGNETO1_RIGHT: "Magneto 1 Right"
  KEY_MAGNETO1_SET: "Set Magneto 1"
  KEY_MAGNETO1_START: "Magneto 1 Start"
  KEY_MAGNETO2_BOTH: "Magneto 2 Both"
  KEY_MAGNETO2_DECR: "Magneto 2 Decrease"
  KEY_MAGNETO2_INCR: "Magneto 2 Increase"
  KEY_MAGNETO2_LEFT: "Magneto 2 Left"
  KEY_MAGNETO2_OFF: "Magneto 2 Off"
  KEY_MAGNETO2_RIGHT: "Magneto 2 Right"
  KEY_MAGNETO2_SET: "Set Magneto 2"
  KEY_MAGNETO2_START: "Magneto 2 Start"
  KEY_MAGNETO3_BOTH: "Magneto 3 Both"
  KEY_MAGNETO3_DECR: "Magneto 3 Decrease"
  KEY_MAGNETO3_INCR: "Magneto 3 Increase"
  KEY_MAGNETO3_LEFT: "Magneto 3 Left"
  KEY_MAGNETO3_OFF: "Magneto 3 Off"
  KEY_MAGNETO3_RIGHT: "Magneto 3 Right"
  KEY_MAGNETO3_SET: "Set Magneto 3"
  KEY_MAGNETO3_START: "Magneto 3 Start"
  KEY_MAGNETO4_BOTH: "Magneto 4 Both"
  KEY_MAGNETO4_DECR: "Magneto 4 Decrease"
  KEY_MAGNETO4_INCR: "Magneto 4 Increase"
  KEY_MAGNETO4_LEFT: "Magneto 4 Left"
  KEY_MAGNETO4_OFF: "Magneto 4 Off"
  KEY_MAGNETO4_RIGHT: "Magneto 4 Right"
  KEY_MAGNETO4_SET: "Set Magneto 4"
  KEY_MAGNETO4_START: "Magneto 4 Start"
  KEY_MASTER_BATTERY_SET: "Set Master Battery"
  KEY_NAV_LIGHTS_SET: "Set Nav Lights"
  KEY_PARKING_BRAKES : "Parking Brake"
  KEY_PAUSE_TOGGLE : "Pause"
  KEY_PROP_PITCH_AXIS_SET_EX1 : "Propeller Pitch"
  KEY_RUDDER_TRIM_LEFT : "Rudder Trim Left"
  KEY_RUDDER_TRIM_RIGHT : "Rudder Trim Right"
  KEY_SHOW_NAVLOG : "Display Navlog"
  KEY_SHOW_VFRMAP : "Display Map"
  KEY_SIM_RATE : "Sim Rate"
  KEY_SIM_RATE_DECR : "Decr Sim Rate"
  KEY_SIM_RATE_INCR : "Incr Sim Rate"
  KEY_SMART_CAMERA_NEXT : "Next Smart Cam Target"
  KEY_SMART_CAMERA_PREVIOUS : "Previous Smart Cam Target"
  KEY_SPOILERS_TOGGLE : "Toggle Spoilers"
  KEY_STROBES_SET: "Set Strobes"
  KEY_TAXI_LIGHTS_SET: "Set Taxi Lights"
  KEY_THROTTLE_AXIS_SET_EX1 : "Throttle"
  KEY_THROTTLE_REVERSE_THRUST_HOLD : "Hold Reverse Thrust"
  KEY_THROTTLE_REVERSE_THRUST_TOGGLE : "Toggle Reverse Thrust"
  KEY_TOGGLE_ALTERNATOR1: "Toggle Alternator 1"
  KEY_TOGGLE_ALTERNATOR2: "Toggle Alternator 2"
  KEY_TOGGLE_ALTERNATOR3: "Toggle Alternator 3"
  KEY_TOGGLE_ALTERNATOR4: "Toggle Alternator 4"
  KEY_TOGGLE_AVIONICS_MASTER: "Toggle Avionics Master"
  KEY_TOGGLE_FEATHER_SWITCHES : "Toggle Feather Switches"
  KEY_TOGGLE_MASTER_ALTERNATOR: "Toggle Alternator Master"
  KEY_TOGGLE_MASTER_BATTERY_ALTERNATOR: "Toggle Master Battery & Alternator"
  KEY_TOGGLE_SMART_CAMERA: "Toggle Smart Cam"
  KEY_VIEW_MODE : "Toggle Cockpit/Ext Cam"
  KEY_XPNDR : "Transponder"
  MENU_BACK : "Menu Back"
  MENU_DOWN : "Menu Down"
  MENU_LEFT : "Menu Left"
  MENU_RIGHT : "Menu Right"
  MENU_UP : "Menu Up"
  MENU_VALID : "Menu Select"
  TOGGLE_COPILOT_DELEGATE_CONTROLS : "Delegate to CoPilot"